security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$z9NwU6dLIMIdmY/ULIBmOeK6iY2cCNXljpY3dU7lBcKBfZCHpJoAO' # password = admin123
                        roles: ['ROLE_ADMIN']
                    user:
                        password: '$2y$13$Kj7Z7M3iJQ3/vkK5gqYh7eyIKw.CEWRABbDd1E0DMZkO.YxwRO4jO' # password = user123
                        roles: ['ROLE_USER']

    firewalls:
        # Disable security for dev tools (profiler, assets, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall â€” handles login, roles, etc.
        main:
            lazy: true
            provider: in_memory
            http_basic:
                realm: 'Trailblaze Admin Area'
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                target: app_login  # After logout, go back to login page

    # Access control rules
    access_control:
        # Public pages (no login required)
        # - { path: ^/(login|register)$, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
        # Regular users can access shop pages
        - { path: ^/shop, roles: ROLE_USER }
        # Admin-only access for dashboard and management pages
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
